name: CMake build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: DEBUG

jobs:
  build:
    name: Running unit tests with ${{matrix.ctest_option}} option
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ctect_option:
          - "-DBESM666_TEST_WITH_VALGRIND=OFF"
          - "-DBESM666_TEST_WITH_VALGRIND=ON"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install valgrind
      run: sudo apt update && sudo apt install -y valgrind

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.ctect_option}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

# @todo #2: Add dummy test using gtest and run it on ci.
#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      run: ctest --test-dir ${{github.workspace}}/build/besm-666
